# Generated by Django 3.2.14 on 2022-08-28 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_reports'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=500)),
                ('profile_image_url', models.URLField(blank=True, default='', max_length=1000)),
                ('linkedin_url', models.URLField(blank=True, default='', max_length=1000)),
                ('hierarchy', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Team',
                'ordering': ['hierarchy'],
            },
        ),
        migrations.AlterModelOptions(
            name='reports',
            options={'ordering': ['-created_on'], 'verbose_name_plural': 'Reports'},
        ),
    ]
