# Generated by Django 3.2.14 on 2022-08-28 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0004_auto_20220828_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='position_adjustment',
            field=models.CharField(blank=True, max_length=800),
        ),
    ]
