# Generated by Django 3.2.14 on 2022-08-28 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0005_team_position_adjustment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='position_adjustment',
            field=models.TextField(blank=True, max_length=800),
        ),
    ]
