# Generated by Django 3.2.14 on 2022-08-28 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0006_alter_team_position_adjustment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_title', models.CharField(max_length=600)),
                ('homepage_title', models.CharField(max_length=1000)),
                ('homepage_subtitle', models.CharField(max_length=2000)),
                ('performance_title', models.CharField(max_length=1000)),
                ('performance_subtitle', models.CharField(max_length=1000)),
                ('strategy_title', models.CharField(max_length=1000)),
                ('strategy_subtitle', models.CharField(max_length=1000)),
                ('strategy_card_title_1', models.CharField(max_length=1000)),
                ('strategy_card_title_2', models.CharField(max_length=1000)),
                ('strategy_card_title_3', models.CharField(max_length=1000)),
                ('strategy_card_content_1', models.CharField(max_length=1000)),
                ('strategy_card_content_2', models.CharField(max_length=1000)),
                ('strategy_card_content_3', models.CharField(max_length=1000)),
                ('team_title', models.CharField(max_length=1000)),
                ('team_subtitle', models.CharField(max_length=1000)),
                ('contact_title', models.CharField(max_length=1000)),
                ('contact_subtitle', models.CharField(max_length=1000)),
                ('disclaimer', models.CharField(max_length=2000)),
            ],
            options={
                'verbose_name_plural': 'Content',
            },
        ),
    ]
