# Generated by Django 3.2.14 on 2022-09-01 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0008_auto_20220828_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='performance_title',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
