# Generated by Django 3.2.14 on 2022-09-01 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0010_auto_20220901_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=150)),
                ('fund_performance', models.IntegerField(default=0)),
                ('market_performance', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Chart Data',
            },
        ),
    ]
