# Generated by Django 3.2.14 on 2023-03-18 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0011_chartdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='show_reports',
            field=models.BooleanField(default=True),
        ),
    ]
